baseurl: http://www.bjornarneson.com
title: 'bjornarneson dot com'
name: 'Bjorn Arneson'
email: mail@bjornarneson.com
slogan: 'Jack of Some Trades'
permalink: /posts/:year/:month/:day/:title/
markdown: rdiscount
rdiscount:
  extensions: [smart]
